version: "3.7"

services:
  banana-logger-bot:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    image: banana-logger-bot:latest
    container_name: Banana-Logger-Bot
    restart: always
    depends_on:
      - banana-logger-db
    networks:
      - default
  banana-logger-db:
    image: mongo:3.6
    container_name: Banana-Logger-Bot-DB
    restart: always
    volumes:
      - ./storage/db:/data/db
      - ./storage/configdb:/data/configdb
    networks:
      - default
networks:
  default:
