import { randomUUID } from "node:crypto";

import type { EventType } from "@/db/client";

import { env } from "./env";

export const Colors = {
  RED: 0xed4245,
  GREEN: 0x57f287,
  YELLOW: 0xfee75c,
  BLURPLE: 0x5865f2,
  FUCHSIA: 0xeb459e,
  WHITE: 0xffffff,
  BLACK: 0x000000,
};

export const baseGalleryEmbedUrl = () =>
  `${env.PUBLIC_URL}/embeds#${randomUUID()}`;

export const BasePlaceholders = ["GUILD_ID"] as const;

export const AuditLogBasePlaceholders = [
  "EXECUTOR_MENTION",
  "EXECUTOR_NAME",
  "EXECUTOR_ID",
  "EXECUTOR_AVATAR",
  "REASON",
] as const;

export const AuditLogChangePlaceholders = [
  "OLD_VALUE",
  "NEW_VALUE",
  "OLD_VALUE_RAW",
  "NEW_VALUE_RAW",
] as const;

export const AuditLogTargetPlaceholders = [
  "TARGET_ID",
  "TARGET_NAME",
  "TARGET_MENTION",
  "TARGET_IMAGE_URL",
] as const;

export const EmbedTemplatePlaceholders = {
  guildUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateDescription: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateIcon: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateSplash: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateDiscoverySplash: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateBanner: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateOwner: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateRegion: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdatePreferredLocale: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateAfkChannel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateAfkTimeout: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateRulesChannel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdatePublicUpdatesChannel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateSafetyAlertsChannel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateMfaLevel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateVerificationLevel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateExplicitContentFilter: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateDefaultMessageNotifications: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateVanityUrlCode: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdatePremiumProgressBarEnabled: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateSystemChannelFlags: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateSystemChannel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateWidgetEnabled: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  guildUpdateWidgetChannel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  channelCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateType: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateTopic: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateNsfw: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  channelUpdateBitrate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateUserLimit: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateRateLimitPerUser: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdatePosition: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdatePermissionOverwrites: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateDefaultAutoArchiveDurations: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateVideoQualityMode: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  memberKick: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  memberBanAdd: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  memberBanRemove: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  memberPrune: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "DELETE_MEMBER_DAYS",
    "MEMBERS_REMOVED",
  ],
  memberUpdateNick: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  memberUpdateDeaf: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  memberUpdateMute: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  memberUpdateAvatar: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  memberUpdateTimeout: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  memberRoleUpdate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "REMOVED_ROLES",
    "ADDED_ROLES",
  ],
  memberMove: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "COUNT",
    "CHANNEL_MENTION",
  ],
  memberDisconnect: [...BasePlaceholders, ...AuditLogBasePlaceholders],
  botAdd: [...BasePlaceholders, ...AuditLogBasePlaceholders],
  roleCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  roleUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  roleUpdateColor: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  roleUpdateHoist: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  roleUpdateMentionable: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  roleUpdatePermissions: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  roleDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  inviteCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "INVITE_URL",
    "INVITE_CODE",
    "INVITE_CHANNEL_MENTION",
    "INVITE_MAX_AGE",
    "INVITE_MAX_USES",
    "INVITE_TEMPORARY",
  ],
  inviteUpdateCode: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    "INVITE_URL",
  ],
  inviteUpdateChannel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    "INVITE_URL",
  ],
  inviteUpdateInviter: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    "INVITE_URL",
  ],
  inviteUpdateMaxUses: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    "INVITE_URL",
  ],
  inviteUpdateMaxAge: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    "INVITE_URL",
  ],
  inviteUpdateTemporary: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    "INVITE_URL",
  ],
  inviteUpdateUses: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    "INVITE_URL",
  ],
  inviteDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "INVITE_URL",
  ],
  webhookCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "WEBHOOK_CHANNEL_MENTION",
  ],
  webhookUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  webhookUpdateAvatar: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  webhookUpdateChannel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  webhookDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  webhookSelfDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  emojiCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  emojiUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  emojiDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  messageDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "AUTHOR_MENTION",
    "AUTHOR_NAME",
    "AUTHOR_ID",
    "AUTHOR_AVATAR",
    "OLD_CONTENT",
    "MESSAGE_URL",
    "CHANNEL_MENTION",
  ],
  messageBulkDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "COUNT",
  ],
  messagePin: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "MESSAGE_URL",
  ],
  messageUnpin: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "MESSAGE_URL",
  ],
  channelOverwriteCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "OVERWRITE_ID",
    "OVERWRITE_TYPE",
    "OVERWRITE_NAME",
  ],
  channelOverwriteUpdate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "OVERWRITE_ID",
    "OVERWRITE_TYPE",
    "OVERWRITE_NAME",
    "PERMISSIONS_CHANGED",
  ],
  channelOverwriteDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "OVERWRITE_ID",
    "OVERWRITE_TYPE",
    "OVERWRITE_NAME",
  ],
  stageInstanceCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "TOPIC",
  ],
  stageInstanceUpdateTopic: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  stageInstanceUpdatePrivacyLevel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  stageInstanceDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  stickerCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "DESCRIPTION",
    "TAGS",
  ],
  stickerUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  stickerUpdateDescription: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  stickerUpdateTags: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  stickerDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  scheduledEventCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
    "DESCRIPTION",
    "LOCATION",
    "START_TIME",
    "END_TIME",
  ],
  scheduledEventUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  scheduledEventUpdateDescription: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  scheduledEventUpdateChannelId: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  scheduledEventUpdateLocation: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  scheduledEventUpdateStatus: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  scheduledEventUpdateEntityType: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  scheduledEventUpdatePrivacyLevel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  scheduledEventUpdateImageHash: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  scheduledEventDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  // Auto-Mod Rules
  autoModRuleCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModRuleUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModRuleUpdateEventType: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModRuleUpdateTriggerType: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModRuleUpdateTriggerMetadata: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModRuleUpdateActions: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModRuleUpdateEnabled: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModRuleUpdateExemptRoles: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModRuleUpdateExemptChannels: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModRuleDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  autoModBlockMessage: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "AUTO_MOD_RULE_NAME",
    "AUTO_MOD_RULE_TRIGGER_TYPE",
    "CHANNEL_MENTION",
  ],
  autoModFlagToChannel: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "AUTO_MOD_RULE_NAME",
    "AUTO_MOD_RULE_TRIGGER_TYPE",
    "CHANNEL_MENTION",
  ],
  autoModTimeout: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "AUTO_MOD_RULE_NAME",
    "AUTO_MOD_RULE_TRIGGER_TYPE",
    ...AuditLogTargetPlaceholders,
    "CHANNEL_MENTION",
  ],
  autoModQuarantine: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "AUTO_MOD_RULE_NAME",
    "AUTO_MOD_RULE_TRIGGER_TYPE",
    ...AuditLogTargetPlaceholders,
  ],
  // Threads
  threadCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  threadUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  threadUpdateArchived: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  threadUpdateLocked: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  threadUpdateAutoArchiveDuration: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  threadUpdateRateLimitPerUser: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  threadUpdateFlags: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  threadDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  // Voice Events
  voiceJoin: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
    "CHANNEL_NAME",
  ],
  voiceLeave: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
    "CHANNEL_NAME",
  ],
  voiceMove: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "OLD_CHANNEL_MENTION",
    "NEW_CHANNEL_MENTION",
  ],
  voiceServerMute: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
    "MUTE_STATUS",
  ],
  voiceServerDeaf: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
    "DEAF_STATUS",
  ],
  voiceSelfMute: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
    "MUTE_STATUS",
  ],
  voiceSelfDeaf: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
    "DEAF_STATUS",
  ],
  voiceStartStream: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
  ],
  voiceStopStream: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
  ],
  voiceStartVideo: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
  ],
  voiceStopVideo: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
    "CHANNEL_MENTION",
  ],
  // Member
  memberLeave: [
    ...BasePlaceholders,
    "USER_MENTION",
    "USER_NAME",
    "USER_ID",
    "USER_AVATAR",
  ],
  // Message Events
  messageUpdate: [
    ...BasePlaceholders,
    "AUTHOR_MENTION",
    "AUTHOR_NAME",
    "AUTHOR_ID",
    "AUTHOR_AVATAR",
    "OLD_CONTENT",
    "NEW_CONTENT",
    "MESSAGE_URL",
    "CHANNEL_MENTION",
  ],
  messageReactionAdd: [
    ...BasePlaceholders,
    "REACTOR_MENTION",
    "REACTOR_NAME",
    "REACTOR_ID",
    "REACTOR_AVATAR",
    "REACTION_EMOJI",
    "REACTION_IMAGE_URL",
    "AUTHOR_MENTION",
    "AUTHOR_NAME",
    "MESSAGE_URL",
    "CHANNEL_MENTION",
  ],
  messageReactionRemove: [
    ...BasePlaceholders,
    "REACTOR_MENTION",
    "REACTOR_NAME",
    "REACTOR_ID",
    "REACTOR_AVATAR",
    "REACTION_EMOJI",
    "REACTION_IMAGE_URL",
    "AUTHOR_MENTION",
    "AUTHOR_NAME",
    "MESSAGE_URL",
    "CHANNEL_MENTION",
  ],
  // Missing Channel Update Fields
  channelUpdateRtcRegion: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateFlags: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateDefaultThreadRateLimitPerUser: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  // Missing Role Update Fields
  roleUpdateIcon: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  // Application Command Permissions
  applicationCommandPermissionUpdate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    "APPLICATION_ID",
    "COMMAND_ID",
    "PERMISSIONS_CHANGED",
  ],
  // Onboarding Events
  onboardingPromptCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  onboardingPromptUpdate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  onboardingPromptDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  onboardingCreate: [...BasePlaceholders, ...AuditLogBasePlaceholders],
  onboardingUpdate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  // Home Settings
  homeSettingsCreate: [...BasePlaceholders, ...AuditLogBasePlaceholders],
  homeSettingsUpdate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
  ],
  // Creator Monetization
  creatorMonetizationRequestCreated: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
  ],
  creatorMonetizationTermsAccepted: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
  ],
  // Missing Channel Update Fields (Forum)
  channelUpdateAvailableTags: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  channelUpdateDefaultReactionEmoji: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  // Missing Scheduled Event Update Fields
  scheduledEventUpdateRecurrenceRule: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  // Soundboard Events
  soundboardSoundCreate: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  soundboardSoundUpdateName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  soundboardSoundUpdateVolume: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  soundboardSoundUpdateEmojiId: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  soundboardSoundUpdateEmojiName: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogChangePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
  soundboardSoundDelete: [
    ...BasePlaceholders,
    ...AuditLogBasePlaceholders,
    ...AuditLogTargetPlaceholders,
  ],
} as const satisfies Record<EventType, string[]>;

export const ALL_EVENTS_CHOICE = "all";
