import type { EventType } from "@/db/client";

export const Colors = {
  RED: 0xed4245,
  GREEN: 0x57f287,
  YELLOW: 0xfee75c,
  BLURPLE: 0x5865f2,
  FUCHSIA: 0xeb459e,
  WHITE: 0xffffff,
  BLACK: 0x000000,
};

export const EmbedTemplatePlaceholders = {
  guildMemberAdd: ["MEMBER_MENTION", "MEMBER_AVATAR"],
  guildMemberRemove: ["MEMBER_MENTION", "MEMBER_AVATAR"],
  messageDelete: [
    "AUTHOR_MENTION",
    "MESSAGE_URL",
    "CHANNEL_MENTION",
    "OLD_CONTENT",
  ],
  messageBulkDelete: [
    "AUTHOR_MENTION",
    "MESSAGE_URL",
    "CHANNEL_MENTION",
    "OLD_CONTENT",
  ],
  messageUpdate: [
    "AUTHOR_MENTION",
    "MESSAGE_URL",
    "CHANNEL_MENTION",
    "OLD_CONTENT",
    "NEW_CONTENT",
  ],
  messageReactionAdd: [
    "REACTOR_MENTION",
    "REACTION_EMOJI",
    "REACTION_IMAGE_URL",
    "AUTHOR_MENTION",
    "MESSAGE_URL",
    "CHANNEL_MENTION",
  ],
  messageReactionRemove: [
    "REACTOR_MENTION",
    "REACTION_EMOJI",
    "REACTION_IMAGE_URL",
    "AUTHOR_MENTION",
    "MESSAGE_URL",
    "CHANNEL_MENTION",
  ],
  guildMemberNicknameChange: ["MEMBER_MENTION", "OLD_NICKNAME", "NEW_NICKNAME"],
  guildMemberAvatarChange: ["MEMBER_MENTION", "OLD_AVATAR", "NEW_AVATAR"],
  guildMemberRoleAdd: ["MEMBER_MENTION", "ROLE_MENTION"],
  guildMemberRoleRemove: ["MEMBER_MENTION", "ROLE_MENTION"],
  guildMemberRoleBulkUpdate: [
    "MEMBER_MENTION",
    "ADDED_ROLES_MENTION",
    "REMOVED_ROLES_MENTION",
  ],
  guildBanAdd: ["MEMBER_BANNED_MENTION", "MOD_MENTION", "REASON"],
  guildBanRemove: [
    "MEMBER_BANNED_MENTION",
    "MOD_MENTION",
    "UNBAN_MOD_MENTION",
    "REASON",
  ],
  guildMemberKick: ["MEMBER_MENTION", "MOD_MENTION", "REASON"],
  guildMemberRulesAccepted: ["MEMBER_MENTION"],
  roleCreate: ["ROLE_MENTION"],
  roleUpdate: ["ROLE_MENTION"],
  roleDelete: ["ROLE_MENTION"],
  invitePosted: ["INVITE_URL"],
  inviteCreate: ["INVITE_URL"],
  inviteDelete: ["INVITE_URL"],
  channelCreate: ["CHANNEL_MENTION"],
  channelUpdate: ["CHANNEL_MENTION"],
  channelDelete: ["CHANNEL_MENTION"],
  channelPermissionUpdate: ["CHANNEL_MENTION"],
  voiceChannelJoin: ["MEMBER_MENTION"],
  voiceChannelMove: ["MEMBER_MENTION"],
  voiceChannelLeave: ["MEMBER_MENTION"],
  voiceChannelMemberMute: ["MEMBER_MENTION"],
  voiceChannelMemberDeafened: ["MEMBER_MENTION"],
  emojiAdd: ["EMOJI_MENTION"],
  emojiUpdate: ["EMOJI_MENTION"],
  emojiDelete: ["EMOJI_MENTION"],
  stickerAdd: ["STICKER_MENTION"],
  stickerUpdate: ["STICKER_MENTION"],
  stickerDelete: ["STICKER_MENTION"],
  botAdd: ["BOT_MENTION"],
  guildUpdate: ["GUILD_MENTION"],
} as const satisfies Record<EventType, string[]>;
