import { EventType } from "@/db/client";

export const EVENT_PRESETS = {
  server: [
    EventType.guildUpdateName,
    EventType.guildUpdateDescription,
    EventType.guildUpdateIcon,
    EventType.guildUpdateSplash,
    EventType.guildUpdateDiscoverySplash,
    EventType.guildUpdateBanner,
    EventType.guildUpdateOwner,
    EventType.guildUpdateRegion,
    EventType.guildUpdatePreferredLocale,
    EventType.guildUpdateAfkChannel,
    EventType.guildUpdateAfkTimeout,
    EventType.guildUpdateRulesChannel,
    EventType.guildUpdatePublicUpdatesChannel,
    EventType.guildUpdateSafetyAlertsChannel,
    EventType.guildUpdateMfaLevel,
    EventType.guildUpdateVerificationLevel,
    EventType.guildUpdateExplicitContentFilter,
    EventType.guildUpdateDefaultMessageNotifications,
    EventType.guildUpdateVanityUrlCode,
    EventType.guildUpdatePremiumProgressBarEnabled,
    EventType.guildUpdateWidgetEnabled,
    EventType.guildUpdateWidgetChannel,
    EventType.guildUpdateSystemChannelFlags,
    EventType.guildUpdateSystemChannel,
    EventType.homeSettingsCreate,
    EventType.homeSettingsUpdate,
  ],
  channels: [
    EventType.channelCreate,
    EventType.channelUpdateName,
    EventType.channelUpdateType,
    EventType.channelUpdateTopic,
    EventType.channelUpdateNsfw,
    EventType.channelUpdateBitrate,
    EventType.channelUpdateUserLimit,
    EventType.channelUpdateRateLimitPerUser,
    EventType.channelUpdatePosition,
    EventType.channelUpdatePermissionOverwrites,
    EventType.channelUpdateDefaultAutoArchiveDurations,
    EventType.channelUpdateVideoQualityMode,
    EventType.channelUpdateRtcRegion,
    EventType.channelUpdateFlags,
    EventType.channelUpdateDefaultThreadRateLimitPerUser,
    EventType.channelUpdateAvailableTags,
    EventType.channelUpdateDefaultReactionEmoji,
    EventType.channelDelete,
    EventType.channelOverwriteCreate,
    EventType.channelOverwriteUpdate,
    EventType.channelOverwriteDelete,
    EventType.threadCreate,
    EventType.threadUpdateName,
    EventType.threadUpdateArchived,
    EventType.threadUpdateLocked,
    EventType.threadUpdateAutoArchiveDuration,
    EventType.threadUpdateRateLimitPerUser,
    EventType.threadUpdateFlags,
    EventType.threadDelete,
  ],
  members: [
    EventType.memberKick,
    EventType.memberBanAdd,
    EventType.memberBanRemove,
    EventType.memberPrune,
    EventType.memberUpdateNick,
    EventType.memberUpdateDeaf,
    EventType.memberUpdateMute,
    EventType.memberUpdateAvatar,
    EventType.memberUpdateTimeout,
    EventType.memberRoleUpdate,
    EventType.memberMove,
    EventType.memberDisconnect,
    EventType.memberJoin,
    EventType.memberLeave,
    EventType.voiceJoin,
    EventType.voiceLeave,
    EventType.voiceMove,
  ],
  roles: [
    EventType.roleCreate,
    EventType.roleUpdateName,
    EventType.roleUpdateColor,
    EventType.roleUpdateHoist,
    EventType.roleUpdateMentionable,
    EventType.roleUpdatePermissions,
    EventType.roleUpdateIcon,
    EventType.roleDelete,
  ],
  messages: [
    EventType.messageDelete,
    EventType.messageBulkDelete,
    EventType.messagePin,
    EventType.messageUnpin,
    EventType.messageUpdate,
    EventType.messageReactionAdd,
    EventType.messageReactionRemove,
    EventType.messageReactionRemoveAll,
    EventType.messageReactionRemoveEmoji,
  ],
  invites: [
    EventType.inviteCreate,
    EventType.inviteUpdateCode,
    EventType.inviteUpdateChannel,
    EventType.inviteUpdateInviter,
    EventType.inviteUpdateMaxUses,
    EventType.inviteUpdateMaxAge,
    EventType.inviteUpdateTemporary,
    EventType.inviteUpdateUses,
    EventType.inviteDelete,
  ],
  expressions: [
    EventType.emojiCreate,
    EventType.emojiUpdateName,
    EventType.emojiDelete,
    EventType.stickerCreate,
    EventType.stickerUpdateName,
    EventType.stickerUpdateDescription,
    EventType.stickerUpdateTags,
    EventType.stickerDelete,
    EventType.soundboardSoundCreate,
    EventType.soundboardSoundUpdateName,
    EventType.soundboardSoundUpdateVolume,
    EventType.soundboardSoundUpdateEmojiId,
    EventType.soundboardSoundUpdateEmojiName,
    EventType.soundboardSoundDelete,
  ],
  moderation: [
    EventType.memberKick,
    EventType.memberBanAdd,
    EventType.memberBanRemove,
    EventType.memberPrune,
    EventType.memberUpdateTimeout,
    EventType.autoModRuleCreate,
    EventType.autoModRuleUpdateName,
    EventType.autoModRuleUpdateEventType,
    EventType.autoModRuleUpdateTriggerType,
    EventType.autoModRuleUpdateTriggerMetadata,
    EventType.autoModRuleUpdateActions,
    EventType.autoModRuleUpdateEnabled,
    EventType.autoModRuleUpdateExemptRoles,
    EventType.autoModRuleUpdateExemptChannels,
    EventType.autoModRuleDelete,
    EventType.autoModBlockMessage,
    EventType.autoModFlagToChannel,
    EventType.autoModTimeout,
    EventType.autoModQuarantine,
  ],
  voice: [
    EventType.voiceJoin,
    EventType.voiceLeave,
    EventType.voiceMove,
    EventType.voiceServerMute,
    EventType.voiceServerDeaf,
    EventType.voiceSelfMute,
    EventType.voiceSelfDeaf,
    EventType.voiceStartStream,
    EventType.voiceStopStream,
    EventType.voiceStartVideo,
    EventType.voiceStopVideo,
  ],
  events: [
    EventType.scheduledEventCreate,
    EventType.scheduledEventUpdateName,
    EventType.scheduledEventUpdateDescription,
    EventType.scheduledEventUpdateChannelId,
    EventType.scheduledEventUpdateLocation,
    EventType.scheduledEventUpdateStatus,
    EventType.scheduledEventUpdateEntityType,
    EventType.scheduledEventUpdatePrivacyLevel,
    EventType.scheduledEventUpdateImageHash,
    EventType.scheduledEventUpdateRecurrenceRule,
    EventType.scheduledEventDelete,
    EventType.stageInstanceCreate,
    EventType.stageInstanceUpdateTopic,
    EventType.stageInstanceUpdatePrivacyLevel,
    EventType.stageInstanceDelete,
  ],
  webhooks: [
    EventType.webhookCreate,
    EventType.webhookUpdateName,
    EventType.webhookUpdateAvatar,
    EventType.webhookUpdateChannel,
    EventType.webhookDelete,
    EventType.webhookSelfDelete,
  ],
  onboarding: [
    EventType.onboardingPromptCreate,
    EventType.onboardingPromptUpdate,
    EventType.onboardingPromptDelete,
    EventType.onboardingCreate,
    EventType.onboardingUpdate,
  ],
  permissions: [
    EventType.channelOverwriteCreate,
    EventType.channelOverwriteUpdate,
    EventType.channelOverwriteDelete,
    EventType.roleCreate,
    EventType.roleUpdatePermissions,
    EventType.roleDelete,
    EventType.applicationCommandPermissionUpdate,
  ],
  "apps-and-bots": [
    EventType.botAdd,
    EventType.applicationCommandPermissionUpdate,
    EventType.integrationCreate,
    EventType.integrationDelete,
    EventType.webhookCreate,
    EventType.webhookUpdateName,
    EventType.webhookUpdateAvatar,
    EventType.webhookUpdateChannel,
    EventType.webhookDelete,
    EventType.webhookSelfDelete,
  ],
  monetization: [
    EventType.creatorMonetizationRequestCreated,
    EventType.creatorMonetizationTermsAccepted,
  ],
} as const satisfies Record<string, EventType[]>;

export type PresetName = keyof typeof EVENT_PRESETS;

export const PRESET_NAMES = Object.keys(EVENT_PRESETS) as PresetName[];
