name: Docker Image CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

jobs:
  pnpm-store-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=ghcr.io/eduardozgz/banana-logger-deps:build-cache
          cache-to: type=registry,ref=ghcr.io/eduardozgz/banana-logger-deps:build-cache,mode=max
          tags: |
            ghcr.io/eduardozgz/banana-logger-deps:latest

  build-bot:
    runs-on: ubuntu-latest
    needs: pnpm-store-cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/bot/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=ghcr.io/eduardozgz/banana-logger-bot:build-cache
          cache-to: type=registry,ref=ghcr.io/eduardozgz/banana-logger-bot:build-cache,mode=max
          tags: |
            ghcr.io/eduardozgz/banana-logger-bot:latest

  build-frontend:
    runs-on: ubuntu-latest
    needs: pnpm-store-cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=ghcr.io/eduardozgz/banana-logger-frontend:build-cache
          cache-to: type=registry,ref=ghcr.io/eduardozgz/banana-logger-frontend:build-cache,mode=max
          tags: |
            ghcr.io/eduardozgz/banana-logger-frontend:latest
          build-args: |
            VITE_DISCORD_CLIENT_ID=${{ vars.VITE_DISCORD_CLIENT_ID }}

  build-backend:
    runs-on: ubuntu-latest
    needs: pnpm-store-cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=ghcr.io/eduardozgz/banana-logger-backend:build-cache
          cache-to: type=registry,ref=ghcr.io/eduardozgz/banana-logger-backend:build-cache,mode=max
          tags: |
            ghcr.io/eduardozgz/banana-logger-backend:latest

  build-db-utils:
    runs-on: ubuntu-latest
    needs: pnpm-store-cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: packages/db/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=ghcr.io/eduardozgz/banana-logger-db-utils:build-cache
          cache-to: type=registry,ref=ghcr.io/eduardozgz/banana-logger-db-utils:build-cache,mode=max
          tags: |
            ghcr.io/eduardozgz/banana-logger-db-utils:latest
